export interface Job {
  id: string
  slug: string
  notification_title: string
  advertisement_number: string
  department: string
  organization: string
  sector:
    | 'banking'
    | 'railway'
    | 'ssc'
    | 'upsc'
    | 'defence'
    | 'teaching'
    | 'state_psc'
    | 'police'
    | 'psu'
    | 'other'
  total_vacancies: number
  education_level: '10th' | '12th' | 'iti' | 'diploma' | 'graduate' | 'pg' | 'phd'
  age_min: number
  age_max: number
  salary_min: number
  salary_max: number
  application_fee_general: number
  application_fee_sc_st: number
  important_dates: {
    notification_date: string
    start_date: string
    last_date: string
    exam_date: string | null
  }
  apply_link: string
  locations: string[]
  tags: string[]
  status: 'published' | 'draft' | 'expired'
  featured: boolean
  posts: Array<{
    post_name: string
    vacancies_total: number
    education_required: string
    age_limit: string
    salary: string
  }>
  created_at: string
}

export const placeholderJobs: Job[] = [
  {
    id: 'sbi-clerk-2026',
    slug: 'sbi-clerk-recruitment-2026',
    notification_title: 'SBI Clerk (Junior Associate) Recruitment 2026',
    advertisement_number: 'CRPD/CR/2026-26/01',
    department: 'Department of Financial Services',
    organization: 'State Bank of India',
    sector: 'banking',
    total_vacancies: 8000,
    education_level: 'graduate',
    age_min: 20,
    age_max: 28,
    salary_min: 23000,
    salary_max: 80000,
    application_fee_general: 750,
    application_fee_sc_st: 0,
    important_dates: {
      notification_date: '2026-02-20',
      start_date: '2026-02-25',
      last_date: '2026-03-25',
      exam_date: '2026-06-15',
    },
    apply_link: 'https://sbi.co.in/careers',
    locations: ['All India'],
    tags: ['banking', 'clerk', 'sbi', 'graduate', 'fresher-friendly'],
    status: 'published',
    featured: true,
    posts: [
      {
        post_name: 'Junior Associate (Customer Support & Sales)',
        vacancies_total: 5500,
        education_required: 'Graduation in any discipline from a recognized university',
        age_limit: '20–28 years (relaxation as per rules)',
        salary: '₹23,000 – ₹80,000 (Basic Pay: ₹19,900)',
      },
      {
        post_name: 'Junior Associate (Inter-branch Settlements)',
        vacancies_total: 1500,
        education_required: 'Graduation with Commerce/Accountancy',
        age_limit: '20–28 years (relaxation as per rules)',
        salary: '₹23,000 – ₹80,000 (Basic Pay: ₹19,900)',
      },
      {
        post_name: 'Junior Associate (Treasury Operations)',
        vacancies_total: 1000,
        education_required: 'Graduation in Finance/Economics/Mathematics',
        age_limit: '20–28 years (relaxation as per rules)',
        salary: '₹23,000 – ₹80,000 (Basic Pay: ₹19,900)',
      },
    ],
    created_at: '2026-02-20T10:00:00Z',
  },
  {
    id: 'rrb-ntpc-02-2026',
    slug: 'rrb-ntpc-recruitment-02-2026',
    notification_title: 'RRB NTPC (Non-Technical Popular Categories) 02/2026',
    advertisement_number: 'CEN 02/2026',
    department: 'Ministry of Railways',
    organization: 'Railway Recruitment Boards',
    sector: 'railway',
    total_vacancies: 11558,
    education_level: '12th',
    age_min: 18,
    age_max: 33,
    salary_min: 19900,
    salary_max: 92300,
    application_fee_general: 500,
    application_fee_sc_st: 250,
    important_dates: {
      notification_date: '2026-02-28',
      start_date: '2026-03-05',
      last_date: '2026-04-15',
      exam_date: '2026-08-10',
    },
    apply_link: 'https://www.rrbapply.gov.in',
    locations: ['All India'],
    tags: ['railway', 'ntpc', '12th-pass', 'graduate', 'large-vacancy'],
    status: 'published',
    featured: true,
    posts: [
      {
        post_name: 'Station Master',
        vacancies_total: 2500,
        education_required: 'Graduation in any discipline',
        age_limit: '18–33 years',
        salary: '₹35,400 – ₹92,300 (Level 6)',
      },
      {
        post_name: 'Traffic Assistant',
        vacancies_total: 3058,
        education_required: 'Graduation in any discipline',
        age_limit: '18–33 years',
        salary: '₹29,200 – ₹73,000 (Level 5)',
      },
      {
        post_name: 'Commercial Cum Ticket Clerk',
        vacancies_total: 4000,
        education_required: '12th Pass (10+2) from recognized board',
        age_limit: '18–30 years',
        salary: '₹19,900 – ₹63,200 (Level 2)',
      },
      {
        post_name: 'Accounts Clerk Cum Typist',
        vacancies_total: 2000,
        education_required: '12th Pass with Commerce; Typing 30 WPM in English',
        age_limit: '18–30 years',
        salary: '₹19,900 – ₹63,200 (Level 2)',
      },
    ],
    created_at: '2026-02-28T09:00:00Z',
  },
  {
    id: 'ssc-chsl-2026',
    slug: 'ssc-chsl-recruitment-2026',
    notification_title: 'SSC CHSL (Combined Higher Secondary Level) 2026',
    advertisement_number: 'SSC/CHSL/2026',
    department: 'Ministry of Personnel, PG & Pensions',
    organization: 'Staff Selection Commission',
    sector: 'ssc',
    total_vacancies: 4500,
    education_level: '12th',
    age_min: 18,
    age_max: 27,
    salary_min: 25500,
    salary_max: 81100,
    application_fee_general: 100,
    application_fee_sc_st: 0,
    important_dates: {
      notification_date: '2026-02-25',
      start_date: '2026-03-01',
      last_date: '2026-04-01',
      exam_date: '2026-07-01',
    },
    apply_link: 'https://ssc.nic.in',
    locations: ['All India'],
    tags: ['ssc', 'chsl', '12th-pass', 'ldc', 'deo', 'postal-assistant'],
    status: 'published',
    featured: true,
    posts: [
      {
        post_name: 'Lower Division Clerk (LDC) / Junior Secretariat Assistant',
        vacancies_total: 2000,
        education_required: '12th Pass from recognized board',
        age_limit: '18–27 years (relaxation as per rules)',
        salary: '₹25,500 – ₹81,100 (Pay Level 2)',
      },
      {
        post_name: 'Postal Assistant / Sorting Assistant',
        vacancies_total: 1500,
        education_required: '12th Pass from recognized board',
        age_limit: '18–27 years (relaxation as per rules)',
        salary: '₹25,500 – ₹81,100 (Pay Level 4)',
      },
      {
        post_name: 'Data Entry Operator (DEO)',
        vacancies_total: 1000,
        education_required: '12th Pass with Computer proficiency (8000 key depressions/hour)',
        age_limit: '18–27 years (relaxation as per rules)',
        salary: '₹25,500 – ₹81,100 (Pay Level 4)',
      },
    ],
    created_at: '2026-02-25T11:30:00Z',
  },
  {
    id: 'upsc-cds-01-2026',
    slug: 'upsc-cds-01-2026',
    notification_title: 'UPSC CDS (Combined Defence Services) Examination (I) 2026',
    advertisement_number: 'UPSC/CDS-I/2026',
    department: 'Ministry of Defence',
    organization: 'Union Public Service Commission',
    sector: 'defence',
    total_vacancies: 457,
    education_level: 'graduate',
    age_min: 20,
    age_max: 24,
    salary_min: 56100,
    salary_max: 177500,
    application_fee_general: 200,
    application_fee_sc_st: 0,
    important_dates: {
      notification_date: '2026-02-12',
      start_date: '2026-02-15',
      last_date: '2026-03-20',
      exam_date: '2026-04-20',
    },
    apply_link: 'https://upsconline.nic.in',
    locations: ['All India (Training Academies)'],
    tags: ['upsc', 'cds', 'defence', 'graduate', 'officer-cadre', 'ima', 'ota', 'navy', 'airforce'],
    status: 'published',
    featured: true,
    posts: [
      {
        post_name: 'Indian Military Academy (IMA)',
        vacancies_total: 200,
        education_required: 'Graduation from a recognized university',
        age_limit: '20–24 years (born between 02-Jul-2002 and 01-Jul-2006)',
        salary: '₹56,100 – ₹1,77,500 (Level 10)',
      },
      {
        post_name: 'Officers Training Academy (OTA) — Men',
        vacancies_total: 100,
        education_required: 'Graduation from a recognized university',
        age_limit: '20–24 years',
        salary: '₹56,100 – ₹1,77,500 (Level 10)',
      },
      {
        post_name: 'Indian Naval Academy',
        vacancies_total: 82,
        education_required: 'B.E./B.Tech in Engineering disciplines',
        age_limit: '20–24 years',
        salary: '₹56,100 – ₹1,77,500 (Level 10)',
      },
      {
        post_name: 'Air Force Academy',
        vacancies_total: 75,
        education_required:
          'Graduation with Physics & Mathematics at 10+2 level, or B.E./B.Tech',
        age_limit: '20–24 years',
        salary: '₹56,100 – ₹1,77,500 (Level 10)',
      },
    ],
    created_at: '2026-02-12T08:00:00Z',
  },
  {
    id: 'ibps-po-2026',
    slug: 'ibps-po-recruitment-2026',
    notification_title: 'IBPS PO (Probationary Officer/Management Trainee) CRP PO/MT-XVI',
    advertisement_number: 'IBPS/CRP-PO/MT-XVI/2026',
    department: 'Department of Financial Services',
    organization: 'Institute of Banking Personnel Selection',
    sector: 'banking',
    total_vacancies: 3049,
    education_level: 'graduate',
    age_min: 20,
    age_max: 30,
    salary_min: 36000,
    salary_max: 120000,
    application_fee_general: 850,
    application_fee_sc_st: 175,
    important_dates: {
      notification_date: '2026-03-01',
      start_date: '2026-03-05',
      last_date: '2026-04-10',
      exam_date: '2026-06-28',
    },
    apply_link: 'https://ibps.in',
    locations: ['All India'],
    tags: ['banking', 'ibps', 'po', 'graduate', 'officer', 'management-trainee'],
    status: 'published',
    featured: true,
    posts: [
      {
        post_name: 'Probationary Officer (PO)',
        vacancies_total: 2049,
        education_required: 'Graduation in any discipline from a recognized university',
        age_limit: '20–30 years (relaxation for SC/ST/OBC/PwBD)',
        salary: '₹36,000 – ₹1,20,000 (Basic Pay: ₹36,000)',
      },
      {
        post_name: 'Management Trainee (MT)',
        vacancies_total: 1000,
        education_required: 'Graduation in any discipline with minimum 55% marks',
        age_limit: '20–30 years (relaxation for SC/ST/OBC/PwBD)',
        salary: '₹36,000 – ₹1,20,000 (Basic Pay: ₹36,000)',
      },
    ],
    created_at: '2026-03-01T07:00:00Z',
  },
  {
    id: 'army-agniveer-2026',
    slug: 'indian-army-agniveer-2026',
    notification_title: 'Indian Army Agniveer Rally Recruitment 2026 (All Categories)',
    advertisement_number: 'Army/Agniveer/2026-01',
    department: 'Ministry of Defence',
    organization: 'Indian Army',
    sector: 'defence',
    total_vacancies: 25000,
    education_level: '10th',
    age_min: 17,
    age_max: 23,
    salary_min: 30000,
    salary_max: 40000,
    application_fee_general: 0,
    application_fee_sc_st: 0,
    important_dates: {
      notification_date: '2026-03-01',
      start_date: '2026-03-10',
      last_date: '2026-04-30',
      exam_date: null,
    },
    apply_link: 'https://joinindianarmy.nic.in',
    locations: [
      'All India',
      'Rally Centers across states',
    ],
    tags: ['army', 'agniveer', '10th-pass', '12th-pass', 'defence', 'youth'],
    status: 'published',
    featured: false,
    posts: [
      {
        post_name: 'Agniveer (General Duty)',
        vacancies_total: 15000,
        education_required: 'Class 10th Pass (SSLC) with 45% aggregate',
        age_limit: '17.5–23 years',
        salary: '₹30,000/month (1st year), ₹33,000 (2nd year)',
      },
      {
        post_name: 'Agniveer (Technical)',
        vacancies_total: 5000,
        education_required: '12th Pass with Physics, Chemistry, Maths (60% aggregate)',
        age_limit: '17.5–23 years',
        salary: '₹30,000/month (1st year), ₹33,000 (2nd year)',
      },
      {
        post_name: 'Agniveer (Clerk/Store Keeper Technical)',
        vacancies_total: 3000,
        education_required: '12th Pass with 60% aggregate; Typing 33 WPM',
        age_limit: '17.5–23 years',
        salary: '₹30,000/month (1st year), ₹33,000 (2nd year)',
      },
      {
        post_name: 'Agniveer (Tradesman)',
        vacancies_total: 2000,
        education_required: 'Class 10th Pass with relevant ITI trade certificate',
        age_limit: '17.5–23 years',
        salary: '₹30,000/month (1st year), ₹33,000 (2nd year)',
      },
    ],
    created_at: '2026-03-01T06:00:00Z',
  },
  {
    id: 'up-police-constable-2026',
    slug: 'up-police-constable-recruitment-2026',
    notification_title: 'UP Police Constable Recruitment 2026',
    advertisement_number: 'UPPRPB/Const/2026-01',
    department: 'Home Department, Government of Uttar Pradesh',
    organization: 'Uttar Pradesh Police Recruitment and Promotion Board',
    sector: 'police',
    total_vacancies: 52699,
    education_level: '12th',
    age_min: 18,
    age_max: 25,
    salary_min: 21700,
    salary_max: 69100,
    application_fee_general: 400,
    application_fee_sc_st: 200,
    important_dates: {
      notification_date: '2026-02-18',
      start_date: '2026-02-22',
      last_date: '2026-03-30',
      exam_date: '2026-07-15',
    },
    apply_link: 'https://uppbpb.gov.in',
    locations: ['Uttar Pradesh'],
    tags: ['police', 'constable', 'up', '12th-pass', 'mega-vacancy', 'physical-test'],
    status: 'published',
    featured: true,
    posts: [
      {
        post_name: 'Constable (Civil Police)',
        vacancies_total: 40000,
        education_required: '12th Pass (Intermediate) from a recognized board',
        age_limit: '18–25 years (relaxation for OBC/SC/ST)',
        salary: '₹21,700 – ₹69,100 (Pay Level 3)',
      },
      {
        post_name: 'Constable (PAC)',
        vacancies_total: 8699,
        education_required: '12th Pass (Intermediate) from a recognized board',
        age_limit: '18–25 years (relaxation for OBC/SC/ST)',
        salary: '₹21,700 – ₹69,100 (Pay Level 3)',
      },
      {
        post_name: 'Constable (Fireman)',
        vacancies_total: 4000,
        education_required: '12th Pass; Physical fitness standards applicable',
        age_limit: '18–25 years',
        salary: '₹21,700 – ₹69,100 (Pay Level 3)',
      },
    ],
    created_at: '2026-02-18T12:00:00Z',
  },
  {
    id: 'krcl-apprentice-2026',
    slug: 'krcl-trainee-apprentice-2026',
    notification_title: 'KRCL Trainee Apprentice Recruitment 2026',
    advertisement_number: 'KRCL/HR/Apprentice/2026-01',
    department: 'Ministry of Railways',
    organization: 'Konkan Railway Corporation Limited',
    sector: 'railway',
    total_vacancies: 190,
    education_level: 'diploma',
    age_min: 18,
    age_max: 25,
    salary_min: 8000,
    salary_max: 9000,
    application_fee_general: 100,
    application_fee_sc_st: 0,
    important_dates: {
      notification_date: '2026-02-28',
      start_date: '2026-03-01',
      last_date: '2026-03-21',
      exam_date: null,
    },
    apply_link: 'https://konkanrailway.com/careers',
    locations: ['Maharashtra', 'Goa', 'Karnataka'],
    tags: ['railway', 'apprentice', 'diploma', 'iti', 'konkan', 'trainee'],
    status: 'published',
    featured: false,
    posts: [
      {
        post_name: 'Graduate Apprentice (Civil Engineering)',
        vacancies_total: 40,
        education_required: 'B.E./B.Tech in Civil Engineering',
        age_limit: '18–25 years',
        salary: '₹9,000/month (stipend)',
      },
      {
        post_name: 'Graduate Apprentice (Electrical Engineering)',
        vacancies_total: 35,
        education_required: 'B.E./B.Tech in Electrical Engineering',
        age_limit: '18–25 years',
        salary: '₹9,000/month (stipend)',
      },
      {
        post_name: 'Technician Apprentice (Mechanical)',
        vacancies_total: 60,
        education_required: 'Diploma in Mechanical Engineering',
        age_limit: '18–25 years',
        salary: '₹8,000/month (stipend)',
      },
      {
        post_name: 'Technician Apprentice (S&T)',
        vacancies_total: 55,
        education_required: 'Diploma in Electronics / Telecommunications',
        age_limit: '18–25 years',
        salary: '₹8,000/month (stipend)',
      },
    ],
    created_at: '2026-02-28T14:00:00Z',
  },
  {
    id: 'nta-ugc-net-2026',
    slug: 'nta-ugc-net-june-2026',
    notification_title: 'NTA UGC NET June 2026 Examination',
    advertisement_number: 'NTA/UGC-NET/June-2026',
    department: 'Ministry of Education',
    organization: 'National Testing Agency',
    sector: 'teaching',
    total_vacancies: 0,
    education_level: 'pg',
    age_min: 0,
    age_max: 0,
    salary_min: 57700,
    salary_max: 182400,
    application_fee_general: 1150,
    application_fee_sc_st: 600,
    important_dates: {
      notification_date: '2026-02-22',
      start_date: '2026-02-25',
      last_date: '2026-04-05',
      exam_date: '2026-06-10',
    },
    apply_link: 'https://ugcnet.nta.nic.in',
    locations: ['All India (Exam Centers)'],
    tags: ['teaching', 'ugc-net', 'pg', 'jrf', 'assistant-professor', 'nta'],
    status: 'published',
    featured: false,
    posts: [
      {
        post_name: 'Junior Research Fellowship (JRF)',
        vacancies_total: 0,
        education_required: 'Post-Graduation with minimum 55% marks in relevant subject',
        age_limit: 'Maximum 30 years (relaxation for SC/ST/OBC/PwBD)',
        salary: '₹31,000/month (JRF fellowship) + HRA',
      },
      {
        post_name: 'Assistant Professor Eligibility',
        vacancies_total: 0,
        education_required: 'Post-Graduation with minimum 55% marks in relevant subject',
        age_limit: 'No upper age limit',
        salary: '₹57,700 – ₹1,82,400 (Pay Level 10)',
      },
    ],
    created_at: '2026-02-22T10:30:00Z',
  },
  {
    id: 'bpsc-70th-2026',
    slug: 'bpsc-70th-combined-exam-2026',
    notification_title: 'BPSC 70th Combined Competitive Examination 2026',
    advertisement_number: 'BPSC/70th CCE/2026',
    department: 'Government of Bihar',
    organization: 'Bihar Public Service Commission',
    sector: 'state_psc',
    total_vacancies: 1929,
    education_level: 'graduate',
    age_min: 20,
    age_max: 37,
    salary_min: 44900,
    salary_max: 209200,
    application_fee_general: 600,
    application_fee_sc_st: 150,
    important_dates: {
      notification_date: '2026-02-10',
      start_date: '2026-02-12',
      last_date: '2026-03-18',
      exam_date: '2026-05-18',
    },
    apply_link: 'https://bpsc.bih.nic.in',
    locations: ['Bihar'],
    tags: ['state-psc', 'bpsc', 'graduate', 'officer', 'bihar', 'civil-services'],
    status: 'published',
    featured: true,
    posts: [
      {
        post_name: 'Deputy Collector / Deputy SP / Other Group A Services',
        vacancies_total: 400,
        education_required: 'Graduation from a recognized university',
        age_limit: '20–37 years (relaxation for SC/ST/OBC/PwBD/Women)',
        salary: '₹44,900 – ₹2,09,200 (Pay Level 11+)',
      },
      {
        post_name: 'Block Development Officer (BDO)',
        vacancies_total: 529,
        education_required: 'Graduation from a recognized university',
        age_limit: '20–37 years',
        salary: '₹44,900 – ₹1,42,400 (Pay Level 10)',
      },
      {
        post_name: 'Revenue Officer / Supply Inspector / Other Group B',
        vacancies_total: 1000,
        education_required: 'Graduation from a recognized university',
        age_limit: '20–37 years',
        salary: '₹44,900 – ₹1,42,400 (Pay Level 10)',
      },
    ],
    created_at: '2026-02-10T09:00:00Z',
  },
]
