name = "sarkarimatch-backend"
main = "workers/publisher/src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "sarkarimatch-db"
database_id = "6f5fc0c6-a18d-49c6-81fe-ddbc322b3cb7"
